### ISSUE TITLE
permission.filter(...) -> exception value is not a function

### ISSUE THREAD

**Issue by slanska** [onury/accesscontrol#1]
Hi there!
First, thanks for an amazing project. Like it a lot and started using in my pet project. 
Second, I faced the following error when trying to apply permission to filter output based on attribute rules. See title. According to Notation.js, value is declared as property (get value() {...}), so should be accessed as **value**, not as **value()** (refer to lib/helper.js:line 98):
``` javascript
    filter(object, attributes) {
        if (!Array.isArray(attributes) || attributes.length === 0) {
            return {};
        }
        let notation = new Notation(object);
        return notation.filter(attributes).value();
    },
```

As a result, calling **permission.filter** crashes with mentioned above exception.

**Comment by onury** [comment]
Excellent catch @slanska. Thanks.
Seems filtering test is also missing in the project.
I've already fixed that and will release shortly.

**Comment by slanska** [comment]
Perfect! That was quick! Thank you!
