### ISSUE TITLE
Expect Object from getGrants

### ISSUE THREAD

**Issue by OR13** [onury/accesscontrol#10]
```
describe('grantList', async () => {

  var grantList = [
    { role: 'admin', resource: 'video', action: 'create:any', attributes: ['*'] }
  ];

  it('should initialize ac from grantList', async () => {
    var ac = new AccessControl(grantList)
    let grants = ac.getGrants()
    console.log(grants)
    })
})
```

Outputs: 
```
[ { role: 'admin',
resource: 'video',
action: 'create:any',
attributes: [ '*' ] } ]
```

I am expecting an object, like in the tests:

https://github.com/onury/accesscontrol/blob/master/lib/AccessControl.js#L130

When i mix my approach:

```
describe('grantList', async () => {
    var grantList = [
        { role: 'admin', resource: 'video', action: 'create:any', attributes: ['*'] }
    ];

    it('should initialize ac from grantList', async () => {
        var ac = new AccessControl(grantList)
        ac
        .grant('user')
        .readAny(['profile', 'video'], ['', '!id', '!password'])
        .createOwn(['profile', 'video'])
        .deleteOwn(['video']);
        // logging underlying grants model
        console.log(ac.getGrants());
    })
})
```

I get this mixd output:

```
[ { role: 'admin',
    resource: 'video',
    action: 'create:any',
    attributes: [ '*' ] },
  user: { profile: { 'read:any': [Array], 'create:own': [Array] },
    video: 
     { 'read:any': [Array],
       'create:own': [Array],
       'delete:own': [Array] } } ]
```

I guess I am expecting the types to be the same.

Really, I'd love to export as a grantList or an Object, depending on the situation.

**Comment by onury** [comment]
Nice catch. Thanks.
The constructor takes the grants parameter as is. This is a bug. It should be processed like the `.setGrants(obj)` method does.

I'll fix this shortly but if this is too urgent pls use `.setGrants()` instead of the constructor for now.

Option to export grants as an object or array was already in todo list. I'll see if it'll make its way to this release.

**Comment by OR13** [comment]
wow, thanks for the quick reply!

Your solution works :)

Before using setGrants I was seeing:

```
TypeError: Cannot read property '$extend' of undefined
```

when checking permissions like so:

```
let permission = ac.can('admin').createAny('video')
```

I'm trying to create an equivalence between your library and an Ethereum Smart contract, I imagine I will have many more questions :)

**Comment by onury** [comment]
You're welcome. I don't have too much knowledge about Ethereum though.

v1.5.2 is released with a fix.

I need time for adding support for exporting grants as a flat list. This is a bit tricky bec. of hierarchical role inheritance. 

Closing this. Pls re-open or create a new issue if needed.
cheers.
