### ISSUE TITLE
Add ability to normalize data object before filtering

### ISSUE THREAD

**Issue by Zauberklavier** [onury/accesscontrol#20]
I stumbled upon this when trying to filter responses from Mongoose queries. In short, every `ObjectId` property turns into an object when passed through `filter()`, which is not the intended representation. I don't think this is specific to Mongoose hence this report.

Suppose a query on an empty Mongoose model `Foo`:
```javascript
let bar = await Foo.findOne().lean()
```
Now do  `JSON.stringify(bar)`:
```json
{
  "_id": "59d4a6ea1960f7053c497508",
  "__v": 0
}
```
Now do `JSON.stringify(permission.filter(bar))`:
```json
{
  "_id": {
    "_bsontype": "ObjectID",
    "id": {
      "type": "Buffer",
      "data": [89, 212, 166, 234, 25, 96, 247, 5, 60, 73, 117, 8]
    }
  },
  "__v": 0
}
```
For now I'm using this as a workaround:
```javascript
permission.filter(JSON.parse(JSON.stringify(bar))) // gross
```

**Comment by onury** [comment]
That's not related to AccessControl. 

I'm not too familiar with MongoDB but, the [documentation](https://docs.mongodb.com/manual/reference/method/ObjectId/) shows that [`_id`](https://docs.mongodb.com/manual/reference/glossary/#term-id) field is a bson-type: [`ObjectId`](https://docs.mongodb.com/manual/reference/bson-types/#objectid).

`JSON.stringify()` converts the `_id` field to string bec. internally it calls [`ObjectId#toString()` method](https://docs.mongodb.com/manual/reference/method/ObjectId.toString/#ObjectId.toString).

Besides, be careful with class objects when filtering. AccessControl will only deal with enumerable properties of the source object; so it should be used to manipulate data objects. It will not deal with preserving the prototype-chain of the given object.

**Comment by Zauberklavier** [comment]
That's true. However I think it'd still be worthwhile to add this as a feature.

The reason is that JSON is a common way to present data to the client, AccessControl should then have the ability to behave consistently with `JSON.stringify()`.

**Comment by onury** [comment]
I'll consider this. But it may not make it to the next release (v2.0.0).

**Comment by jyotman** [comment]
@Zauberklavier You can also do `permission.filter(bar.toJSON())` as mongoose provide the `toJSON()` method on its objects.

**Comment by Zauberklavier** [comment]
Thanks :+1:

@jyotman The `toJSON()` doesn't work that way, it is there so `JSON.stringify()` calls it and uses whatever it returns to do its job. If I remember correctly it's an alias for `toObject()`.

**Comment by onury** [comment]
Sorry, decided not to add this kind of partial support for Mongoose, it would be very hard to maintain. 

Besides, it seems you're not passing an actual data object. `Query#lean()` returns `Query` self instance. So you're passing a `Query` object to AccessControl, which is not proper. See Mongoose docs for [lean](http://mongoosejs.com/docs/api.html#query_Query-lean). 

I guess you should call [`.exec()`](http://mongoosejs.com/docs/api.html#query_Query-exec) on that query to get a [document array](http://mongoosejs.com/docs/api.html#types-documentarray-js). 

Example:
```js
Model.find().lean().exec(function (err, docs) {
    const data = docs.toObject(); // returns a native js Array of plain js objects
    const filtered = permission.filter(data);
});
```
