### ISSUE TITLE
Example application 

### ISSUE THREAD

**Issue by vanessasoutoc** [onury/accesscontrol#27]
Some example available??

**Comment by onury** [comment]
Fully documented. You need more?
- [API Reference](https://onury.io/accesscontrol/?api=ac)
- [F.A.Q.](https://onury.io/accesscontrol/?content=faq)
- [Guide](https://onury.io/accesscontrol/?content=guide)
- [Express.js Example](https://github.com/onury/accesscontrol#expressjs-example)
