### ISSUE TITLE
Checking of posession based on role?

### ISSUE THREAD

**Issue by senser1** [onury/accesscontrol#28]
I'm trying to check for possession for the following scenario;

Roles:

- User
- PrimaryContact
- Admin

In the system there are Contacts and Accounts. Contacts are linked to Accounts by AccountID. Some Accounts have a parent Account, linked by ID. 

I would like to set grants for the following:

- User role may read own Contacts, 

- PrimaryContacts may read any Contact that belongs to all Accounts

- Admin may read any Contact. 

So for a User reading his own Contact, the isOwn check is something like 

`const isOwn = contact.accountID === user.accountID`

The users with the PrimaryContact and Admin role have no other special attributes as a 'normal' user (besides having different role assigned on the user in the database) so the only IsOwn check I can think of is directly checking for a certain role. Is this the way to go?

**Comment by onury** [comment]
What's the difference between `may read any Contact that belongs to all Accounts` and  `may read any Contact`? It seems both can read any contact.

**Comment by onury** [comment]
By the way, `PrimaryContact` does not seem a proper role name/definition. A role should define a purpose of a user. Contacts - in your case - seems to (or should) represent a resource not a role. Being "primary" is a setting or attribute which can change over time. 

And how and why do you determine that a contact is "primary"?

**Comment by senser1** [comment]
The difference between `may read any Contact that belongs to all Accounts` and `may read any Contact` is that the latter can read all Contact entities in the system regardless of Accounts. The first means all Contacts that are related to the Account of the user and all Contacts of related Accounts. 

The role `PrimaryContact` can be read like the primary contact of the person who handles all business in this case. The 'contact' part in this example causes some confusion I guess, but in this case its a valid role I guess. This role is something that is agreed upon, its not hard defined. 

On my user registration I have an array of user roles that are put on req.user. Those user roles I use in `ac.can(user.roles).readOwn('Contact)` etc. The user that is a PrimaryContact has that role on their roles array.

**Comment by onury** [comment]
If I get you correctly, what you want to achieve is a hierarchical contact list. 
For example, `john` is the parent account of user `jane`; so `john`s contacts include all `jane`s (which include all contacts from the child accounts, if there are any).

Is this the case?

**Comment by senser1** [comment]
That is correct. One Account contains several Contacts, some Accounts have child Accounts that also contain Contacts. I would like to give the User role access to their own Contacts (Contacts linked to their direct Account) and PrimaryContact role should be able to access all Contacts (Contacts linkt to direct Account but also all Contacts from the linked child Contacts)!

**Comment by onury** [comment]
From what I understand, I'll try to show you an implementation:

#### `Contacts` data
Let's say the data structure of `Contacts` is like this;
```js
[
  {
    "name": "John Doe",
    "contacts": [
      {
        "name": "Jane Doe",
        "contacts": [...] // goes deep
      }
    ]
  },
  ... // more first-level contacts
]
```
#### Configure Grants:
_I'll rename `PrimaryContact` role to `businessManager` for this example._

We'll grant `admin` to read `any` contacts _"in any contacts tree"_.
```js
ac.grant('admin').readAny('Contacts')
```
The `user` role will be granted access only for _1st level of contacts_ in a contacts tree:
```js
   .grant('user').readOwn('Contacts', ['*', '!contacts'])
```
The `bussinesManager` role will be granted access for one or multi-level contacts; as long as it's related (in it's **own** tree).
```js
  .grant('bussinesManager').readOwn('Contacts');
```

Now, we've done most of it. But, **own** requires an input; so that you can check for ownership / possession.

#### Endpoint for getting contacts — by account ID:

Notice when and how we're checking the ownership of the resource below. This is an endpoint that itself has a parameter for subclassing data.
```js
app.get('/:accountId/contacts', (req, res) => {
    const isOwn = req.params.accountId === req.user.accountId;
    const permission = isOwn
        ? ac.can(req.user.role).readOwn('Contacts')
        : ac.can(req.user.role).readAny('Contacts');
    
    if (permission.granted) {
        getContactsByAccountID(req.params.accountId).then(data => {
            res.json(permission.filter(data));
        });
    } else {
        res.status(403).end();
    }
});
```

What you were doing (`contact.accountID === user.accountID`) implies you're checking ownership for each and every contact item, which is not efficient. It means, you'll need to iterate over all existing contact records. That's certainly bad. 

The data should be fetched with this information in the first place. In other words, for example if you're selecting this data from a DB, this kind of check should be in your `WHERE` clause.

#### Endpoint for getting all contacts:
Such as a section of an administration panel. As a preference, we don't have any parameters in this route. So we'll simply target all (or any) contacts.
```js
app.get('/admin-panel/lists/contacts', (req, res) => {
    const permission = ac.can(req.user.role).readAny('Contacts');
    if (permission.granted) {
        getAllContacts().then(data => {
            res.json(permission.filter(data));
        });
    } else {
        res.status(403).end();
    }
});
```

Does this cover your use case?

**Comment by senser1** [comment]
I understand that checking for ownership via supplied query parameters is indeed better. However for that to work, I have to design the API so that if a user wants to receive all account information with all contacts, to do this in multiple requests (i.e. they have to do multiple gets for each accountID to /:accountID/contacts instead of going to /contacts where they receive the data based on there permissions) right? 

I'm pretty new to REST api design, but that seems a bit of a hassle. Also, if admins log in to see what a user sees (and more), a separate endpoint is not really convenient since this has to be handled in the frontend as well, although its doable of course.

Do you consider it a good option to first check for permissions in the controller (i.e. const canReadAll = ac.can(user.roles).readAll(contacts).granted and pass this boolean to the logic that handles data retrieval? This way, I can retrieve data based on the grants model. Then before passing it to the user, I can filter via AccessControl before returning JSON.

**Comment by onury** [comment]
> ...I have to design the API so that if a user wants to receive all account information with all contacts, to do this in multiple requests...

If this `user` role is not granted unlimited access as `admin`, there has to be an input or a setting/attribute that limits output. If a user can read other account contacts, you need to define a policy for which accounts they can read.

> ...if admins log in to see what a user sees (and more), a separate endpoint is not really convenient since this has to be handled in the frontend as well...

All is done in the backend. It's should not be handled in the frontend. You just handle the representation in the frontend. I don't get how you'll achieve this without different endpoints or parameters.

> Do you consider it a good option to first check for permissions in the controller (i.e. const canReadAll = ac.can(user.roles).readAll(contacts).granted and pass this boolean to the logic that handles data retrieval...

That's one way to optimize data retrieval as noted in my previous post. As long as all access control is done on the server side, you can use both the `granted` result and attributes to fetch data accordingly. e.g. if `.readOwn().granted` returns `true` you fetch data A and for `.readAny().granted` you fetch data A to Z. You can also select fields by using `premission.attributes`, if designed that way.
