### ISSUE TITLE
How do i filter fields of element in array?

### ISSUE THREAD

**Issue by owu365** [onury/accesscontrol#3]
I try to find out the way to filtering fields of element in array, I try this `!ary[*].foo ` and `!ary.foo`, they both doesn't work.

**Comment by onury** [comment]
The `.filter()` method only filters **object properties**.
You can pass a single object or array of objects.

### Example:
```js
ac.grant('user').createOwn('account', ['*', '!foo']);
// ...
var data = [{ foo: 1, baz: 'a' }, { foo: 2, baz: 'b' }];
var permission = ac.can('user').createOwn('account');
console.log(permission.filter(data));
// —> [{ baz: 'a' }, { baz: 'b' }]
```

_Note: AccessControl depends on [Notation](https://github.com/onury/notation) for glob notation and filter functionality._
