### ISSUE TITLE
Possibility of Express Middleware for perm checking

### ISSUE THREAD

**Issue by hillct** [onury/accesscontrol#32]
I'm trying to work out how I might be able to perform an access control permission check using a code structure of the form:
```js
  app.get('/admin/users',
    setRender('admin/users/search'),
    setRedirect({auth: '/'}),
    havePerm.readAny('profile'),
    adminusers.searchProfile);	// Users Search/results
```
rather than the current Express.js example methodology which amounts to predefining each permissions check and testing it within what is effectively the controller of an MVC application. It seems that such an express middleware would simply subclass the `ac.can()` method, returning an express-appropriate response rather than the true/false value, but I don't want to reproduce effort, if someone (3rd party) has already done this, or it's on the roadmap, completed in an unreleased branch somewhere.

Similarly, and more trivially, it might be worthwhile to include a mongoose plugin that inserts a role property in a known location in user models, to facilitate the above permission checking style, being performed where it should be in an MVC application.

If this is already out there, and I've simply overlooked it, please kindly point me to the relevent code/project. If not, I'm willing to undertake this feature development, but having taken a cursory look at the accesscontrol codebase, I'd need a little guidance as to the code structure, in order to implement it efficiently.

Thanks,
Colin

**Comment by onury** [comment]
Hi Colin. I understand the need but I'm not willing to couple AccessControl with a framework or library. Not in this main repo at least. For this to be clean and maintainable, we need to embrace [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle).

I'm also currently not planning on releasing an official express middleware or mongoose plugin. I'd love to see them being developed though. You're very welcome to write one! I'll try and answer if you'll have questions.

As far as I know, there is some efforts for [express integration](https://github.com/pawangspandey/accesscontrol-middleware) by @pawangspandey. (no affiliation)

**Comment by hillct** [comment]
@onury Thanks for the quick reply. Your sentiments regarding SRP are quite reasonable, and I've felt the same about my projects over the years. I took a look at @ pawangspandey's efforts, which don't look like they'll meet my needs. Looks like I'll be tackling this one. I'm leaning toward stubbing out my own CRUD chain methods off .can/havePerm because so far it seems subclassing for chained calls in express middleware is structurally near impossible.

**Comment by onury** [comment]
You don't have to use chained methods.  
i.e. see [#permission](https://onury.io/accesscontrol/?api=ac#AccessControl#permission) in API reference.

**Comment by onury** [comment]
Closing this. Feel free to continue if you have further questions.
