### ISSUE TITLE
createOwn vs createAny

### ISSUE THREAD

**Issue by turakvlad** [onury/accesscontrol#37]
Hi, @onury!

At first, I would like to thank you for such a great library!

I have one questions about `createOwn` and `createAny` methods. I don't understand how to use them from a logical point of view. If I have `readOwn` / `readAny` it's clear for me that the user of some role can read only his own resource or can read any resources (e.g. resources of the other users). The same with `updateOwn` / `updateAny` - the user can update only his own resource or any resources. And the last one is `deleteOwn` / `deleteAny` - for example, the user can delete only his own resource but the admin can delete any resources (e.g. resources of the other users).

But what about `createOwn` and `createAny`. Let's imagine that I have two roles:
- user
- admin

Also, in my DB I have the `posts` table. The user and admin can create posts.

How should I design my AC? 

Let's take this grants:
```
let grantsObject = {
    admin: {
        posts: {
            'create:any': ['*'],
            'read:any': ['*'],
            'update:any': ['*'],
            'delete:any': ['*']
        }
    },
    user: {
        posts: {
            'create:own': ['*'],
            'read:own': ['*'],
            'update:own': ['*'],
            'delete:own': ['*']
        }
    }
};

const ac = new AccessControl(grantsObject);
```

What does `create:any` for the `admin` role mean? Does it mean that the admin can create posts for any other users (e.g. the admin can create the post and assign its `id` to some user)? I am confused with this logic.

And what about `create:own` for the `user` role? Does it mean that the user can create the posts only ... for himself? 

I have read the [guide](https://onury.io/accesscontrol/?content=guide) and [FAQ](https://onury.io/accesscontrol/?content=faq) and I understand that the developer (e.g. me) should make decisions but it's hard for me to understand the idea of `createOwn` and `createAny` concepts.

Thank you for your time.

**Comment by awHamer** [comment]
Hi, it might reference to your own business logic, depends on what the policy you have for `own`.
If the own records - are records which were created by a user (`creator_id` automatically added) so I think `create:any` and `create:own` the same things.

But if your business logic says that OWN records are records which were assigned to you by someone else, that this is a big difference. `create:own` allows you to create a record and assign it to you only, for example. `create:any` allows you to create a record and assign it to somebody...It's just a my vision, anyway it can be controlled by attributes access...

Maybe it was made the way like this just for the consistency purposes... Also curious about this.

**Comment by onury** [comment]
Hi @turakvlad. Thanks and you're welcome.

First of all, you do not need to make use of each and every action/possession for each role and resource. Use only what makes sense for your application.

> What does `create:any` for the `admin` role mean? Does it mean that the admin can create posts for any other users (e.g. the admin can create the post and assign its `id` to some user)?

Actually, that's a question only you and your app can answer.
- If that's what you need, that's definitely proper: 
_"admins creating user posts on other user's behalf"_
example pseudo logic: Users may ask admins to post on their behalf.
example post: _`"I won't be answering until next week."`_
- In some other app logic, it could mean:
_"admins creating admin posts on any user-timeline"_
example pseudo logic: Admins inspect timelines for improper/offensive content.
example post: _`"This user account is suspended"`_

Within your app logic, to make sense of this; you should first define what "own" and "any" stands for (for what role and resource) and do these possessions need distinguished control of access. 

### A Detailed Example:

**Sales representatives** are calling a list of registered customers on the phone and; 
- Sell these customer some products. 

You could represent this in AC as: 
```js
ac.grant('salesRep').createAny('order')
```
**Customers** 
- Can of course, buy products themselves (create),
- And view/modify if they want to.. (read/update)
- They cannot delete the order record but mark the order "canceled" (update)
```js
ac.grant('customer')
  .createOwn('order')
  .readOwn('order')
  .updateOwn('order');
```
**Accountants** 
- Can only view the orders. (read)
```js
ac.grant('accountant').readAny('order');
```
**Sales reps**. 
- Cannot delete an order. 
- They need to file an order-delete-request to their managers.. (create "odr")
 This is only for the orders they've created. (own)
```js
ac.grant('salesRep').createOwn('odr')
  .readOwn('odr').deleteOwn('odr') // can read/delete odr if they need to
```
**Sales managers** 
- Can view order-delete-requests, (read "odr")
- If they see fit, they'll mark the delete request "accepted" (update "odr") and delete the order.
- Actually, they can do anything with the orders. (c/r/u/d "order")
```js
ac.grant('salesManager')
  .readAny('odr').updateAny('odr')
  .createAny('order').readAny('order').updateAny('order').deleteAny('order')
```

Hope this helps.

**Comment by onury** [comment]
@awHamer 

> ... If the own records - are records which were created by a user (`creator_id` automatically added) so I think `create:any` and `create:own` the same things.

Technically yes but logically, users are only creating their own accounts. So, for better semantics; `create:own` is more suitable here if you're making general use of possessions in your app.

> ... But if your business logic says that OWN records are records which were assigned to you by someone else, that this is a big difference. 

Yes. But the app can both allow users to assign/create resources to/for others — and also allow them to create their own resources at the same time.

> `create:own` allows you to create a record and assign it to you only, for example. 

True.

> `create:any` allows you to create a record and assign it to somebody...

And yourself. ("any" also covers "own").

> It's just my vision, anyway it can be controlled by attributes access...
> Maybe it was made the way like this just for the consistency purposes... Also curious about this.

Sorry didn't get this part. How do you mean?

**Comment by awHamer** [comment]
>> It's just my vision, anyway it can be controlled by attributes access...
Maybe it was made the way like this just for the consistency purposes... Also curious about this.

> Sorry didn't get this part. How do you mean?

I meant this is just how I understand it.
Assign to somebody (set `user_id` to someone else) can be also controlled like this
`create:any: ["name,user_id,!moderator_id, ..."]`. 

> Maybe it was made the way like this just for the consistency purposes

Here I meant that another approach about reason why you made "create:any" or "create:own" (that may confuse), to keep consistent naming like "$action:$possession"...But I realized that I was wrong (possession will be set to `any` automatically if omit). So now the topic is clear to me. Thanks.

**Comment by turakvlad** [comment]
@awHamer, @onury, thanks a lot, guys. That was very helpful for me!
