### ISSUE TITLE
Department level access

### ISSUE THREAD

**Issue by gauravsoni1** [onury/accesscontrol#39]
Suppose I have the following roles
1. Employee
2. Manager
All the users belong to departments

Manager A can access documents of department A, 
Manager B can access documents of department B

How can this be implemented using accesscontrol ? cause as per my understanding we have 
can -> any or can -> all

**Comment by onury** [comment]
It's up to how you design the application..  
_(It's either "any" or "own" department docs)_

```js
ac.grant('manager').readOwn('depDocs');

app.get('/department/:depId/docs', (req, res) => {
    const depId = parseInt(req.params.depId, 10);
    const userDepartment = await getUserDep(req.user.id);
    const can = ac.can(req.user.role);
    const permission = depId === userDepartment.id
        ? can.readOwn('depDocs')
        : can.readAny('depDocs');
    if (permission.granted) {
        const depDocs = await getDepDocs(depId);
        if (!depDocs) {
            res.status(404).end(); // not found
        } else {
            res.json(permission.filter(depDocs));
        }
    } else {
        res.status(403).end(); // forbidden
    }
}
```

**Comment by gauravsoni1** [comment]
@onury Appreciate the detailed reply and thanks for the awesome library

**Comment by onury** [comment]
You're welcome.
