### ISSUE TITLE
Chain Queries

### ISSUE THREAD

**Issue by girards** [onury/accesscontrol#40]
I'm working on a project using AccessControl, it would be nice if there was a way of chaining queries like so :

`ac.can('user').createOwn(xx).readAny(yy)`

If not possible what is the best way to do it besides a `&&` condition.

Thanks

**Comment by onury** [comment]
You can query multiple roles (union'ed) at once  
e.g. `ac.can(['user', 'admin']).create(resource)`

But querying for multiple actions at once doesn't make sense to me. 
What's your real-life use case?

**Comment by girards** [comment]
I found a fix by checking access separately, I'm still going to explain the situation, maybe there's another simpler solution.

Basically I'm in a situation where as a `verifier` I can call a route and  I can "verify" an object, by doing this, it updates a submission from "pending" to "verified" plus creates another object, and I want to check if the user can 'createAny(SECOND_OBJECT) and `updateAny(FIRST_OBJECT)`.

**Comment by onury** [comment]
Well, it seems when the submission is updated to "verified", the object is auto-created. So you could simply only check permission for `update` action. The resulting `create` action is done by system, not the user/role.

Let's put it this way: 
When some other privileged role updates the first object to "verified"; is there any case that the second object is NOT created?

**Comment by onury** [comment]
Closing this. Pls re-open if needed.
