### ISSUE TITLE
get a list of flattened permissions

### ISSUE THREAD

**Issue by harryhazza77** [onury/accesscontrol#53]
Hi, this library is awesome!

using getGrants('superadmin') gives me the internal hash table with inherited permissions but i'd like a list of permissions for my 'superadmin' user with the inheritance chain resolved i.e. flattened out. Is there a method for this?

**Comment by onury** [comment]
Thanks. Check out [`AccessControl#getInheritedRolesOf()`](https://onury.io/accesscontrol/?api=ac#AccessControl#getInheritedRolesOf) method.

**Comment by harryhazza77** [comment]
hi [AccessControl#getInheritedRolesOf](https://onury.io/accesscontrol/?api=ac#AccessControl#getInheritedRolesOf) give me flat list of roles for a given role, but i'd like a flattened list of permissions. I am currently working around it by using the following to build up a flattened list of permissions.

```
  const roles = ac.getRoles();
  const resources = ac.getResources().filter(x => x !== '$extend');
  const operations = ['create', 'read', 'update', 'delete'];
  const permissions = ['Own', 'Any'];
```
