### ISSUE TITLE
How do I get the 'grantsObject' or 'grantList' 

### ISSUE THREAD

**Issue by chiarelli** [onury/accesscontrol#56]
How do I get the 'grantsObject' or 'grantList' from an AccessControl object already instantiated, ie the inverse process of "const ac = new AccessControl (grantsObject);" or "" const ac = new AccessControl (grantList); "?

**Comment by onury** [comment]
Please read the docs: [#getGrants()](https://onury.io/accesscontrol/?api=ac#AccessControl#getGrants)

**Comment by gausie** [comment]
@onury this endpoint only gets you the grantsObject not the grantsList. Also it would be nice to export a typing for each of those.
