### ISSUE TITLE
Help wanted: Any suggestion how to deal with access rights that depend on the status (value of an attribute) of a resource

### ISSUE THREAD

**Issue by goofy2k** [onury/accesscontrol#63]
I develop a pool site where users can Create predictions of game results. As long as a game has not yet started (started is an attribute of a game object) , users are allowed to read only their own predictions. Once game.started is true they can also read predictions of others. How to implement this with accesscontrol?

**Comment by onury** [comment]
That's up to your app. Simple example would be:
```js
const permission = game.started
    ? ac.can(role).readAny('predictions')
    : ac.can(role).readOwn('predictions');

return permission.granted ? authorized() : notAuthorized();

```
Pls [read the docs](http://onury.io/accesscontrol/?api=ac).

**Comment by goofy2k** [comment]
Thanks for your fast response, Onur.

I do not yet understand it. I will read the docs better, first.

Apparently it is possible to define grants based on context rather than
ownership and role alone?
Fred

Op vr 25 jan. 2019 20:59 schreef Onur Yıldırım <notifications@github.com:

**Comment by onury** [comment]
I've updated the code sample in my previous post.

**Comment by goofy2k** [comment]
That's nearer to what I look for! I'll start practicing with the module to
discover how it works.

Fred

Op vr 25 jan. 2019 20:59 schreef Onur Yıldırım <notifications@github.com:

**Comment by goofy2k** [comment]
Especially the F.A.Q. is very useful, as it very well describes some concepts and definitions!
