### ISSUE TITLE
Filtering for nested object doesn't seem to be working

### ISSUE THREAD

**Issue by mikesparr** [onury/accesscontrol#64]
Version: `2.2.1`

I pass an object to `permission.filter` and it has a nested object and I'm trying to omit it from response data.

# Example
### Created role permission
```
  const adminSurrogate = connection.manager.create(Permission, {
    action: "create:any",
    attributes: "*, !password, !ip, !surrogatePrincipal.ip, !surrogatePrincipal.password",
    resource: "surrogate",
  });
```

### Log the permission object after CAN
After performing the `.can` it returns a permission object that is `granted` and I print the object:
```
{"_":{"attributes":["*","!password","!ip","!surrogatePrincipal.ip","!surrogatePrincipal.password"],"role":["user","admin"],"resource":"surrogate"}}
```

### Result
I expect the nested object `surrogatePrincipal.password` to be omitted but it's still there. The `password` field is omitted, but other fields in `attributes` still remain.
```
{"id":2,"firstName":"Basic","lastName":"User","email":"user@example.com","avatar":null,"country":null,"timeZone":null,"language":null,"ip":null,"age":21,"roles":[{"id":"user","description":"Authenticated user with basic privileges"}],"surrogateEnabled":true,"surrogatePrincipal":{"id":3,"firstName":"Admin","lastName":"User","email":"admin@example.com","password":"$2b$10$YkIwUtvigAM1n245IzgFKOMlpWH2yPLyAicwDKr5eF46oV1D8dWgS","avatar":"http://example.com/me/1234567.jpg","country":"US","timeZone":"America/Mountain","language":"en_US","ip":"FE80:0000:0000:0000:0202:B3FF:FE1E:8329","age":30}}
```

**Comment by mikesparr** [comment]
I'm unsure if it matters, but I actually set the `password` field to `undefined` in code. I'm curious if performing filter on record and field in attributes doesn't exist creates some error and it skips all other fields?

**Comment by mikesparr** [comment]
**Aha!** - that is the issue.

If a field in `attributes` is undefined, the `permission.filter` does not filter the rest of the fields.

 * expect it to filter all fields in attributes even if one is not present

**Comment by onury** [comment]
@mikesparr thanks for reporting. I'll look into this tonight.

**Comment by onury** [comment]
@mikesparr I cannot reproduce this. I used your exact example and it filters as expected.
None of the excluded properties exist in the output. 
See tested code: [ac-issue-64.zip](https://github.com/onury/accesscontrol/files/2838854/ac-issue-64.zip)

I think, the problem is you're reading that data for a user with 2 roles. 
(see `"role":["user","admin"]` part when you log the permission instance)
I guess `admin` role has full attrs privilege (i.e. `['*']`) and you're checking permission like this:
```js
const perm = ac.can(['admin', 'user']).read('surrogate');
```
So the result includes all the properties, unfiltered..
Let me know if this is the case.
Until then I'll mark this issue as _invalid_.

**Comment by mikesparr** [comment]
You are right. Sorry. After I moved the `filter` it worked as expected but I thought it was because of the `undefined` when in reality I was calling filter on a response from async function that returned user in nested object.

Just to confirm I tested working scenario and failing and confirmed it was my mistake.

## Works fine
```
var AccessControl = require("accesscontrol")

const testModel = {
  admin: {
    surrogate: {
      ["create:any"]: ["*", "!password", "!ip", "!surrogatePrincipal.password"],
    }
  },
  user: {
    video: {
      ["read:own"]: ["*"]
    }
  }
};

const ac = new AccessControl(testModel);

const permission = ac.can(["admin", "user"]).createAny("surrogate");

console.log(permission.granted);

const testUser = {
  id: "12345",
  email: "test@example.com",
  password: "changeme",
  ip: "255.255.255.0",
  surrogatePrincipal: {
    id: "54321",
    email: "admin@example.com",
    password: "weakpass",
    ip: null
  }
};

permission.filter(testUser);
```

## Fails ( was trying to filter a different object - invalid bug )
```
var AccessControl = require("accesscontrol")

const testModel = {
  admin: {
    surrogate: {
      ["create:any"]: ["*", "!password", "!ip", "!surrogatePrincipal.password"],
    }
  },
  user: {
    video: {
      ["read:own"]: ["*"]
    }
  }
};

const ac = new AccessControl(testModel);

const permission = ac.can(["admin", "user"]).createAny("surrogate");

console.log(permission.granted);

const testUser = {
  id: "12345",
  email: "test@example.com",
  password: "changeme",
  ip: "255.255.255.0",
  surrogatePrincipal: {
    id: "54321",
    email: "admin@example.com",
    password: "weakpass",
    ip: null
  }
};

testUser.password = undefined;

const getUser = async () => {
  return {user: testUser, token: "abc12345"};
}

permission.filter(await getUser());
```

**Comment by onury** [comment]
No problem.
