### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by duongdev** [onury/accesscontrol#68]
I don't see this project be updated recently. I am considering using this project in my next production product and I want to ask you if you are having plan to keep maintain and develop this project?

Thanks.

**Comment by onury** [comment]
Fair question! I wrote this to be used in a couple of projects (currently in production). I'm overly occupied with other work so it's been a while since I released an update but I'll definitely make time as soon as possible.

**Comment by duongdev** [comment]
Ok. Thanks for your response. Hope to see this project keep maintained.
