### ISSUE TITLE
Plans on saving access control in a database

### ISSUE THREAD

**Issue by bodo22** [onury/accesscontrol#7]
Are there any plans on saving the access control lists in a database?
Do I understand correctly that all access control infos are lost if i stop the application it's implemented in?

**Comment by onury** [comment]
AccessControl.js sticks to [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle). It does not do any database operations. That's your app's responsibility.

Grants are stored in memory. So it's fast when you query them.
If you get the grants from a database or a JSON file; and pass them to an AccessControl instance, you lose nothing.
```js
let ac = new AccessControl();
fs.readFile('./ac-grants.json', (content) => {
    let grants = JSON.parse(content);
    ac.setGrants(grants);
});
```

But if you're build the grants via AccessControl, then you should persist it to a database or maybe write to a JSON file.
```js
ac.grant('role1').createAny('resource1')
   .grant('role2').createAny('resource2')
   .grant('role3').readAny('resource2')
   // ...

let grants = ac.getGrants();
fs.writeFile('./ac-grants.json', grants, callback);
```
