### ISSUE TITLE
throw error if does not have access to attributes

### ISSUE THREAD

**Issue by rained23** [onury/accesscontrol#70]
Hi,

Thanks for the nice access control package.

I have a use case where we wanted to tell the client side that they don't have access to the following attribute when they try to access it. But right now the AC only check the roles and allow to filter the attribute, in other words, "gracious" style. 

Is there a function for me to inform the roles that their access is denied because they requested the attributes that they don't have access.

Right now I think I can compare the attributes pre and post filter if it's not equal, I can throw an error but this will require me to do the same checking like the filter if I want to know which attributes that they don't have access.

**Comment by Ahmadtawfik-10** [comment]
I think that u have to do it manually!
Can u tell me what is your solution?
thanks.

**Comment by onury** [comment]
Maybe you can use `permission.attributes` property which will return a glob notation array such as `['*', '!record.id']`. You might filter out the items with a `!` prefix and display.
