### ISSUE TITLE
Can it be used on the frontend ?

### ISSUE THREAD

**Issue by bhamon-dot** [onury/accesscontrol#74]
Hello,

Great work @onury !
I am going to implement accesscontrol in my company express.js APIs.
It matches pretty much exactly what we need.

We were also wondering if this could be used in our Vue apps ? 
I don't see any reason not to but I would like your advice on this.

We would have an API returning basically the whole grants array and then using accesscontrol to facilitate the process of displaying what the connected user has access to.

Would that work or am I missing something ?

**Comment by yangyaochia** [comment]
Following this.
as @bhamon-dot said, I plan to user ac to control the display of html elements, and I don't want to make queries for specific element every time.

I am using angular and use pipe to determine the existence of specific html elements
```
transform(resource: string, subResource?: string, action?: string, possession?: string, args?: any): boolean {
    let permission = this.accesscontrolService.currentUserAC.permission({
      role: this.accesscontrolService.currentUserGroups,
      resource: resource, 
      action: action ? action: AccessAction.READ,
      possession: possession ? possession : 'any'
    })
return permission.granted
```

**Comment by eltronix** [comment]
Hey did this work out for you guys @bhamon-dot & @yangyaochia.

cc @onury, would this approach work on the frontend?

**Comment by eltronix** [comment]
If anyone else is wondering, my preliminary tests on `Angular 8` show that it works perfectly so I'll go ahead and use it in both our client and server.

**Comment by bhamon-dot** [comment]
We have been using it with Vue and it works like a charm.

**Comment by noclat** [comment]
As it's based on memory and framework-agnostic, you can use it on the front-end the same way you'd use it on the back-end. And the cool part is that you can share a single ACL declaration between the front-end and the back-end (if you have hands on it). I've wrote an article about that, and even though it's been written for Next.js, the strategy can be replicated anywhere:
https://dev.to/noclat/unify-acl-across-front-end-and-back-end-with-next-js-and-nextauth-js-5ban

**Comment by onury** [comment]
You can use it on frontend with any framework, as mentioned. I'd suggest that you never pass the full grants list to the browser. It might expose information such as hidden/forbidden sections of your app. Pass only the current user's grants, "on-demand" if you can. If you're using SSR, you can render permitted content.
