### ISSUE TITLE
mistake in a code snippet in documentation  

### ISSUE THREAD

**Issue by sourabhkumawat** [onury/accesscontrol#75]
I found your work very interesting and I am very enthusiastic to learn from you, I followed the Access Control documentation and I found that there are some mistakes in the code snippets in the documentation which can be confusing for someone who is new to javascript. please if you can review your code snippets once that would be great.
![Annotation 2019-10-31 105139](https://user-images.githubusercontent.com/22614040/67921367-6e5d8180-fbcd-11e9-99de-ea9f68cdbfab.png)
 
like in this snippets I found console.log is wrong so if you could fix this small issue I will be pleased

**Comment by onury** [comment]
Thanks. 

[`console.log()`](https://developer.mozilla.org/en-US/docs/Web/API/console) is valid javascript. Re-open if you meant something else.
