### ISSUE TITLE
 Complexity is O(amount of roles) is bad, shall it be O(1)?

### ISSUE THREAD

**Issue by donDonald** [onury/accesscontrol#78]
Hello guys,
As to me roles are handled(passed) as array, for instance AccessControl.hasRole iterates over array, and it's not a single place. 

Amount of roles can be 10 or 100 or what ever(at least in my case). It's performance goal for sure.
I believe that roles shall be handled as Object, in this case no need to iterate and shall be O(1).

It's not necessarily a bug but  have to be reviewed at least.

**Comment by onury** [comment]
All granted roles are already handled as an object in memory, not an array.

If you're referring to the argument `roles` passed to `hasRole()` method, it requires a string or an array of strings to check for existence of one or more roles. 100 roles for a single user is not likely, it'd be poor design.
