### ISSUE TITLE
Can we define role, action and resource in database. If required fetch from database and use it to grant access? 

### ISSUE THREAD

**Issue by avinash2222** [onury/accesscontrol#82]

**Comment by Ojooluwaseun** [comment]
You can persist your grants in database and pass grants to AccessControl constructor as an array fetched from DB like so:

// grant list fetched from DB (to be converted to a valid grants object, internally)

let grantList = [
{ role: 'admin', resource: 'video', action: 'create:any', attributes: ', !views' },
{ role: 'admin', resource: 'video', action: 'read:any', attributes: '' },
{ role: 'admin', resource: 'video', action: 'update:any', attributes: ', !views' },
{ role: 'admin', resource: 'video', action: 'delete:any', attributes: '' },
{ role: 'user', resource: 'video', action: 'create:own', attributes: ', !rating, !views' },
{ role: 'user', resource: 'video', action: 'read:any', attributes: '' },
{ role: 'user', resource: 'video', action: 'update:own', attributes: ', !rating, !views' },
{ role: 'user', resource: 'video', action: 'delete:own', attributes: '' }
];

const ac = new AccessControl(grantList);

**Comment by avinashsingh2222** [comment]
@Ojooluwaseun  thanks

**Comment by yf-hk** [comment]
So how to update it when data changes?

**Comment by bayaraajr** [comment]
> So how to update it when data changes?

Restart the node server .
