### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by ao-alex** [onury/accesscontrol#84]
Checking if this is still maintained or not.

**Comment by scandinave** [comment]
it's seems to no. But you can find this project [https://github.com/bluebirds-blue-jay/access-control](https://github.com/bluebirds-blue-jay/access-control) that is a fork of this accesscontrol.

**Comment by SylvainEstevez** [comment]
In case someone crosses this issue, Bluejay's `access-control` is NOT a fork of this module but is a bit inspired by it (I'm the author). Pull requests to add functionality to https://github.com/bluebirds-blue-jay/access-control are welcome though 👍

**Comment by vegerot** [comment]
> it's seems to no. But you can find this project https://github.com/bluebirds-blue-jay/access-control that is a fork of this accesscontrol.

This is false. https://github.com/bluebirds-blue-jay/access-control/issues/33#issuecomment-731501691
