### ISSUE TITLE
Filter creates anwanted fields

### ISSUE THREAD

**Issue by 1mohammad7** [onury/accesscontrol#92]
I'm using mongoose-paginate-v2 to paginate my doccuments.when I get the docs from db, the format is like this:
`
{
docs:[ requested documents],
page: ...
....
}
`
when I use filter on docs array, instead of filtering, it modifies it and creates unwanted fields:

`   "docs": [
            {
                "$__": {
                    "strictMode": true,
                    "selected": {
                        "password": 0
                    },
                    "getters": {
                        "profileView": {
                            "$init": true
                        }
                    },
                    "_id": {
                        "_bsontype": "ObjectID",
                        "id": {
                            "type": "Buffer",
                            "data": [
                                95,
                                94,
                                16,
                                4,
                                98,
                                8,
                                156,
                                8,
                                236,
                                35,
                                179,
                                155
                            ]
                        }
                    },
                    "wasPopulated": false,
                   .........
                },
                "isNew": false,
                "$locals": {},
                "$op": null,
                "_doc": {
                    MY_DOCS (unfiltered)
    }
}`

**Comment by 1mohammad7** [comment]
I fixed it , it had nothing to do with accesscontrol, it was because I didn't use plain mongoose object. I passed `lean=true` to mongoose-paginate and it worked

**Comment by 1mohammad7** [comment]
I have another problem now , when I lean the objects so that I don't get _doc , etc.. , I get an Object for all my fields that are type ObjectId instead of String representation.. like so:

`{"user":{"_bsontype":"ObjectID","id":{"type":"Buffer","data":[95,94,16,4,98,8,156,8,236,35,179,155]}}
`

how can I filter without making unwanted fields (Without Leaning) or not having ObjectIds represented by Strings?

**Comment by 1mohammad7** [comment]
I found something odd. when I filter my result with **inclusion** instead of **exclusion**  , it works fine:
my result when I filter like this:
`{ role: 'admin', resource: 'user_profile', action: 'read:any', attributes: '_id ,firstName'}`
is:
`{
                "_id": "5f5e100462089c08ec23b39b",
                "firstName": "john"
            },`
as you can see _id is represented by String.


but when I change my filter to:
`    { role: 'admin', resource: 'user_profile', action: 'read:any', attributes: '* ,!phoneNumber' },
`
the result will be:
`
            {
                "_id": {
                    "_bsontype": "ObjectID",
                    "id": {
                        "type": "Buffer",
                        "data": [
                            95,
                            94,
                            16,
                            4,
                            98,
                            8,
                            156,
                            8,
                            236,
                            35,
                            179,
                            155
                        ]
                    }
                },
                "addresses": []
.....
,`

now as you can see, ObjectIds are not represented as String.

**Comment by onury** [comment]
This too has nothing to do with AccessControl. Note that this library should be used to manipulate data objects with enumerable properties. It will NOT deal with preserving the prototype-chain of the given object or objects with circular references, or buffers, etc..
